name: geo1101ahn3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - affine=2.3.0
  - attrs=19.3.0
  - blas=1.0
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cfitsio=3.470
  - cgal=5.0.1
  - cgal-cpp=5.0.1
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.9.2
  - curl=7.69.1
  - eigen=3.3.7
  - expat=2.2.9
  - fiona=1.8.13
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.0.4
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.64.3
  - gmp=6.2.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.9
  - jpeg=9c
  - json-c=0.13.1
  - jsoncpp=1.8.4
  - kealib=1.4.13
  - krb5=1.17.1
  - laspy=1.7.0
  - lastools=20171231
  - laszip=3.4.3
  - laz-perf=1.4.4
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libdap4=3.20.6
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=3.0.4
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=12.2
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mpfr=4.0.2
  - munch=2.5.0
  - ncurses=6.1
  - nitro=2.7.dev6
  - numpy=1.18.4
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - owslib=0.20.0
  - pcre=8.44
  - pdal=2.1.0
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.87.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - pthread-stubs=0.4
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python=3.6.9
  - python-dateutil=2.8.1
  - python-pdal=2.3.3
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.3.1
  - rasterio=1.1.4
  - readline=8.0
  - requests=2.23.0
  - scipy=1.4.1
  - setuptools=46.4.0
  - shapely=1.7.0
  - six=1.14.0
  - snuggs=1.4.7
  - sqlite=3.30.1
  - tbb=2020.1
  - tiledb=1.7.7
  - tk=8.6.10
  - tzcode=2020a
  - urllib3=1.25.8
  - wheel=0.34.2
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - startin==0.6.0
    - toml==0.10.0
    - sphinx_rtd_theme==0.5.0
prefix: /home/maartenjong/anaconda3/envs/geo1101ahn3
